version: "3.3"
services:
  # db:
  #   container_name: forum-example-db
  #   restart: always
  #   image: forum-example-db
  #   build:
  #     context: ./db
  #   volumes:
  #     - db:/var/lib/postgresql/data
  #   env_file:
  #     - ./.env
  #   networks:
  #     - network
  #   ports:
  #     - 5432:5432
  graphql:
      container_name: workshop-spatial-graphql
      restart: always
      image: workshop-spatial-graphql
      build:
          context: ./graphql
      env_file:
          - ./.env
      # depends_on:
      #     - db
      networks:
          - network
      ports:
          - 5433:5433
      command: ["--subscriptions", "--watch", "--dynamic-json", "--no-setof-functions-contain-nulls", "--no-ignore-rbac", "--port", "5000", "--show-error-stack=json", "--extended-errors", "hint,detail,errcode", "--append-plugins", "@graphile-contrib/pg-simplify-inflector,@graphile/postgis,postgraphile-plugin-connection-filter,postgraphile-plugin-connection-filter-postgis", "--skip-plugins", "graphile-build:NodePlugin", "--simple-collections", "only", "--graphiql", "/", "--enhance-graphiql", "--allow-explain", "--enable-query-batching", "--legacy-relations", "omit", "--connection", "postgres://postgres:postgis@localhost/workshop_graphql", "--schema", "app_public"]
networks:
  network:
